<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1d60a84c399304f0fbf594e527925613
{
    public static $files = array (
        '04c6c5c2f7095ccf6c481d3e53e1776f' => __DIR__ . '/..' . '/mustangostang/spyc/Spyc.php',
    );

    public static $prefixLengthsPsr4 = array (
        'J' =>
        array (
            'Jaybizzle\\CrawlerDetect\\' => 24,
        ),
        'D' =>
        array (
            'DeviceDetector\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jaybizzle\\CrawlerDetect\\' =>
        array (
            0 => __DIR__ . '/..' . '/jaybizzle/crawler-detect/src',
        ),
        'DeviceDetector\\' =>
        array (
            0 => __DIR__ . '/..' . '/matomo/device-detector',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1d60a84c399304f0fbf594e527925613::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1d60a84c399304f0fbf594e527925613::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1d60a84c399304f0fbf594e527925613::$classMap;

        }, null, ClassLoader::class);
    }
}
